version: "3.8"

services:
  lexical-database:
    image: postgres:14
    environment:
      POSTGRES_DB: lexical
      POSTGRES_USER: lexical
      POSTGRES_PASSWORD: password
    volumes:
      - lexical-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  lexical-database:
