name: Lint & Build

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  # Allow manual workflow trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🌱 Checkout to the branch
        uses: actions/checkout@v3
      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install NextJS
        run: |
          npm install next@latest react@latest react-dom@latest typescript @types/react @types/node
      - name: 📚 npm run lint
        run: |
            cd ./src
            npm run lint
            cd ..
      - name: ⚙️ npm install and build
        run: |
          cd ./src
          npm install
          npm run build --if-present
          cd ..
      - name: 🧹 Cleanup
        run: rm ${{ github.workspace }}/Nextjs-site.zip
