# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - openai-app-etnfkognnuav6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrcoreg41c.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e5d626a730874c5489abe6607c22ff62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f330b7a565d449593d1254d2a841d27 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrcoreg41c.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5d626a730874c5489abe6607c22ff62 }}/mycompanycopilot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openai-app-etnfkognnuav6'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_85a04dd6c4834a52bcb73c15d337e069 }}
        images: 'acrcoreg41c.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e5d626a730874c5489abe6607c22ff62 }}/mycompanycopilot:${{ github.sha }}'